### ISSUE TITLE
DE Catalog update not working

### ISSUE THREAD

**Issue by nylocx** [chartcatalogs/scripts#4]
It looks like the DE Catalog update is not working anymore ,14 of the URLs seem to be outdated. I'm not sure where the scripts are called to update the code myself.

**Comment by nohal** [comment]
If the problem is in the script, post a pull request here. But I doubt that as we have exactly the data we get from ELWIS via https://www.elwis.de/DE/dynamisch/IENC/enc-dateien/ienc_feed.xml as far as I can tell.
If their update procedure got broken and they do not update the Atom feed correctly, it has to be reported to them, not here.

**Comment by nylocx** [comment]
Thanks for the info I did not know about the feed.xml. I thought this is based on some scraping of the ELWIS IENC Website. I send them a mail and maybe cook up something based on bs4 or selenium.

**Comment by nylocx** [comment]
I have opened a ticket at the IT department responsible for the ELWIS stuff but if anyone in the meantime stumbles across this, here is what I temporary used to have an up-to-date DE catalog (This does not handle newly added entries only updates existing ones).

The only thing you need to provide is a github token with gist creation permission (https://github.com/settings/tokens) as the GH_TOKEN environment variable. Than you can visit the printed url to get the [raw_url](https://gist.githubusercontent.com/nylocx/722d788bfea59afaa7dd23c6cdaa127a/raw/9c896c1cf4a171d3b956a20a6f875f67bec2f72c/DE_IENC_Catalog.xml) and create a custom catalog with this in OpenCPN.

```python
import os
import re

import requests
from bs4 import BeautifulSoup

markup = requests.get("https://www.elwis.de/DE/dynamisch/IENC/").text
soup = BeautifulSoup(markup, features="html.parser")

files = [f"{a['href'].split('=')[-1]}.zip" for a in soup("a", class_="aintern")]

catalog = requests.get(
    "https://raw.githubusercontent.com/chartcatalogs/catalogs/master/DE_IENC_Catalog.xml"
).text

for file in files:
    catalog = re.sub(rf"{file.split('_')[0]}_[\d-]+(_\d+)+.zip", file, catalog)

query_url = "https://api.github.com/gists"
data = {
    "public": True,
    "files": {
        "DE_IENC_Catalog.xml": {
            "content": catalog
        },
    }
}
headers = {"Authorization": f"token {os.getenv('GH_TOKEN')}"}

r = requests.post(query_url, headers=headers, json=data)

print(r.json())
```
